### ISSUE TITLE
Include silently fails

### ISSUE THREAD

**Issue by mlabbe** [bluebrown/go-template-cli#17]
I am using {{ include "some bad file.tmpl" . }} in a template, and when the file doesn't exist, it just silently adds nothing.  I would love an option or a default where missing files immediately halt processing and generate an error.  

Thank you for your time

**Comment by mlabbe** [comment]
Hey, here are a couple pull requests that solve the issue:

https://github.com/bluebrown/go-template-cli/pull/18
https://github.com/bluebrown/treasure-map/pull/1

Thanks for the helpful tool!

**Comment by bluebrown** [comment]
Hi, would you mind rebasing your PRs so they only change what is necessary?

**Comment by mlabbe** [comment]
Sorry - I am not going to have the dev time to  spare rebase them in both of your repos.  The cherry pick approach should work.
